- name: Run training pipeline
  env:
    MONGO_URI: ${{ secrets.MONGO_URI }}
  run: |
    export PYTHONPATH=$(pwd)
    python -m app.pipelines.training_pipeline
  run: |
    pwd
    ls
    ls app
    export PYTHONPATH=$(pwd)
    python -m app.pipelines.training_pipeline
